import 'package:flutter/material.dart';

import '../services/ai_rate_limit_service.dart';
import '../services/gemini_service.dart';
import '../core/theme.dart';

/// Chat interface grounded in the text extracted from one PDF.
class ChatScreen extends StatefulWidget {
  final String pdfContent;
  final String documentName;

  // Optional injections keep the screen testable without making real calls.
  final GeminiService? geminiService;
  final AiRateLimitService? rateLimitService;

  const ChatScreen({
    super.key,
    required this.pdfContent,
    required this.documentName,
    this.geminiService,
    this.rateLimitService,
  });

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final TextEditingController _inputController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  final FocusNode _inputFocusNode = FocusNode();
  final List<_ChatMessage> _messages = [];

  late final AiRateLimitService _rateLimitService;
  GeminiService? _geminiService;
  String? _configurationError;
  int? _remainingQuestions;
  bool _isSending = false;

  @override
  void initState() {
    super.initState();
    _rateLimitService = widget.rateLimitService ?? AiRateLimitService();

    try {
      _geminiService = widget.geminiService ?? GeminiService.fromEnvironment();
    } on GeminiServiceException catch (error) {
      _configurationError = error.userMessage;
    }

    final longDocument =
        widget.pdfContent.length > GeminiService.maxPdfCharacters;
    _messages.add(
      _ChatMessage.assistant(
        'Ask me anything about “${widget.documentName}”. '
        '${longDocument ? 'For this long document, I will select the excerpts most relevant to each question. ' : ''}'
        'Answers are generated by AI, so verify important details.',
      ),
    );

    if (_configurationError case final error?) {
      _messages.add(_ChatMessage.assistant(error, isError: true));
    }
    _loadAllowance();
  }

  Future<void> _loadAllowance() async {
    final status = await _rateLimitService.getStatus();
    if (!mounted) return;
    setState(() => _remainingQuestions = status.remaining);
  }

  Future<void> _sendMessage() async {
    final question = _inputController.text.trim();
    if (question.isEmpty || _isSending) return;

    _inputController.clear();
    _inputFocusNode.unfocus();
    setState(() {
      _messages.add(_ChatMessage.user(question));
      _isSending = true;
    });
    _scrollToBottom();

    try {
      final service = _geminiService;
      if (service == null) {
        throw GeminiServiceException(
          _configurationError ??
              'Gemini is not configured. Add the API key to .env.',
        );
      }

      // Consume the local allowance immediately before the network request.
      // Failed extraction/configuration therefore never costs a question.
      final allowance = await _rateLimitService.tryConsumeQuestion();
      if (!mounted) return;
      setState(() => _remainingQuestions = allowance.remaining);

      if (!allowance.allowed) {
        throw const GeminiServiceException(
          'You have used all 15 AI questions for today. Your local allowance '
          'resets tomorrow.',
        );
      }

      final response = await service.sendMessage(widget.pdfContent, question);
      if (!mounted) return;
      setState(() => _messages.add(_ChatMessage.assistant(response)));
    } on GeminiServiceException catch (error) {
      if (!mounted) return;
      setState(
        () => _messages.add(
          _ChatMessage.assistant(error.userMessage, isError: true),
        ),
      );
    } catch (_) {
      if (!mounted) return;
      setState(
        () => _messages.add(
          _ChatMessage.assistant(
            "Couldn't process the request. Please try again.",
            isError: true,
          ),
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isSending = false);
        _scrollToBottom();
      }
    }
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted || !_scrollController.hasClients) return;
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOut,
      );
    });
  }

  @override
  void dispose() {
    _inputController.dispose();
    _scrollController.dispose();
    _inputFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: colors.surface,
      appBar: AppBar(
        titleSpacing: 0,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Chat with AI',
              style: TextStyle(
                color: colors.onSurface,
                fontSize: 17,
                fontWeight: FontWeight.w700,
              ),
            ),
            SizedBox(
              width: 190,
              child: Text(
                widget.documentName,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(color: context.appColors.textSecondary, fontSize: 12),
              ),
            ),
          ],
        ),
        actions: [
          if (_remainingQuestions case final remaining?)
            Padding(
              padding: const EdgeInsets.only(right: 14),
              child: Center(
                child: Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 5,
                  ),
                  decoration: BoxDecoration(
                    color: colors.surfaceContainerHighest.withValues(alpha: 0.3),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '$remaining/${AiRateLimitService.dailyLimit} left',
                    style: TextStyle(
                      color: context.appColors.textSecondary,
                      fontSize: 11,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              controller: _scrollController,
              padding: const EdgeInsets.fromLTRB(16, 20, 16, 12),
              itemCount: _messages.length + (_isSending ? 1 : 0),
              itemBuilder: (context, index) {
                if (_isSending && index == _messages.length) {
                  return const _TypingBubble();
                }
                return _MessageBubble(message: _messages[index]);
              },
            ),
          ),
          _buildComposer(colors),
        ],
      ),
    );
  }

  Widget _buildComposer(ColorScheme colors) {
    return Container(
      decoration: BoxDecoration(
        color: colors.surface,
        border: Border(top: BorderSide(color: context.appColors.border)),
      ),
      child: SafeArea(
        top: false,
        child: Padding(
          padding: const EdgeInsets.fromLTRB(14, 10, 10, 10),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Expanded(
                child: TextField(
                  key: const Key('ai-chat-input'),
                  controller: _inputController,
                  focusNode: _inputFocusNode,
                  enabled: !_isSending,
                  minLines: 1,
                  maxLines: 4,
                  textCapitalization: TextCapitalization.sentences,
                  decoration: InputDecoration(
                    hintText: 'Ask about this PDF…',
                    hintStyle: TextStyle(color: context.appColors.textSecondary),
                    filled: true,
                    fillColor: colors.surfaceContainerHighest.withValues(alpha: 0.3),
                    contentPadding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 12,
                    ),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(22),
                      borderSide: BorderSide.none,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              IconButton.filled(
                key: const Key('ai-chat-send'),
                tooltip: 'Send question',
                onPressed: _isSending ? null : _sendMessage,
                style: IconButton.styleFrom(
                  backgroundColor: colors.primary,
                  foregroundColor: Colors.white,
                  disabledBackgroundColor: context.appColors.border,
                ),
                icon: const Icon(Icons.arrow_upward_rounded),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

enum _MessageAuthor { user, assistant }

class _ChatMessage {
  final _MessageAuthor author;
  final String text;
  final bool isError;

  const _ChatMessage._({
    required this.author,
    required this.text,
    this.isError = false,
  });

  factory _ChatMessage.user(String text) =>
      _ChatMessage._(author: _MessageAuthor.user, text: text);

  factory _ChatMessage.assistant(String text, {bool isError = false}) =>
      _ChatMessage._(
        author: _MessageAuthor.assistant,
        text: text,
        isError: isError,
      );
}

class _MessageBubble extends StatelessWidget {
  final _ChatMessage message;

  const _MessageBubble({required this.message});

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;
    final isUser = message.author == _MessageAuthor.user;
    final bubbleColor = isUser
        ? colors.primary
        : message.isError
        ? context.appColors.primaryContainer
        : colors.surface;
    final textColor = isUser
        ? Colors.white
        : message.isError
        ? colors.primary
        : colors.onSurface;

    return Align(
      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        constraints: BoxConstraints(
          maxWidth: MediaQuery.sizeOf(context).width * 0.78,
        ),
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 11),
        decoration: BoxDecoration(
          color: bubbleColor,
          borderRadius: BorderRadius.only(
            topLeft: const Radius.circular(18),
            topRight: const Radius.circular(18),
            bottomLeft: Radius.circular(isUser ? 18 : 5),
            bottomRight: Radius.circular(isUser ? 5 : 18),
          ),
          border: isUser
              ? null
              : Border.all(
                  color: message.isError ? colors.primary : context.appColors.border,
                ),
        ),
        child: SelectableText(
          message.text,
          style: TextStyle(color: textColor, fontSize: 14, height: 1.45),
        ),
      ),
    );
  }
}

class _TypingBubble extends StatelessWidget {
  const _TypingBubble();

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 12),
        decoration: BoxDecoration(
          color: colors.surface,
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: context.appColors.border),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(
              width: 14,
              height: 14,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: colors.primary,
              ),
            ),
            const SizedBox(width: 10),
            Text(
              'Gemini is reading…',
              style: TextStyle(color: context.appColors.textSecondary, fontSize: 13),
            ),
          ],
        ),
      ),
    );
  }
}
